apiVersion: v2
name: outline
description: This chart deploys an outline wiki instance.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

maintainers:
  - name: leonsteinhaeuser
    email: leonsteinhaeuser@gmail.com
    url: https://github.com/leonsteinhaeuser

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.3.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.66.1"

dependencies:
  # https://github.com/minio/minio/tree/master/helm/minio
  - name: minio
    version: 4.0.14
    repository: https://charts.min.io/
    condition: minio.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha
  - name: postgresql-ha
    version: 9.4.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
  # https://github.com/bitnami/charts/tree/master/bitnami/redis
  - name: redis
    version: 17.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
