apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-s3
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey }}
  AWS_REGION: {{ .Values.s3.region }}
  AWS_S3_UPLOAD_BUCKET_URL: {{ .Values.s3.bucketUrl }}
  AWS_S3_UPLOAD_BUCKET_NAME: {{ .Values.s3.bucketName }}
  AWS_S3_UPLOAD_MAX_SIZE: {{ .Values.s3.maxUploadSize }}
  AWS_S3_FORCE_PATH_STYLE: {{ .Values.s3.maxUploadSize }}
  AWS_S3_ACL: {{ .Values.s3.acl }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-db
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: postgres://{{ .Values.outline.db.user }}@{{ .Values.outline.db.host }}:5432/{{ .Values.outline.db.database }}?sslmode={{ .Values.outline.db.sslmode }}&password={{ .Values.outline.db.password }}
  DATABASE_CONNECTION_POOL_MIN: {{ .Values.outline.db.connectionPoolMin }}
  DATABASE_CONNECTION_POOL_MAX: {{ .Values.outline.db.connectionPoolMax }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-redis
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: {{ .Values.outline.redis.url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-mail
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_HOST: {{ .Values.outline.mail.host }}
  SMTP_PORT: {{ .Values.outline.mail.port }}
  SMTP_USERNAME: {{ .Values.outline.mail.user }}
  SMTP_PASSWORD: {{ .Values.outline.mail.password }}
  SMTP_FROM_EMAIL: {{ .Values.outline.mail.from }}
  SMTP_SECURE: {{ .Values.outline.mail.secure }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-authentication
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.outline.authentication.google }}
  GOOGLE_CLIENT_ID: {{ .Values.outline.authentication.google.clientId }}
  GOOGLE_CLIENT_SECRET: {{ .Values.outline.authentication.google.clientSecret }}
  {{ end }}
  {{ if .Values.outline.authentication.azure }}
  AZURE_CLIENT_ID: {{ .Values.outline.authentication.azure.clientId }}
  AZURE_CLIENT_SECRET: {{ .Values.outline.authentication.azure.clientSecret }}
  AZURE_RESOURCE_APP_ID: {{ .Values.outline.authentication.azure.app_id }}
  {{ end }}
  {{ if .Values.outline.authentication.azure }}
  AZURE_CLIENT_ID: {{ .Values.outline.authentication.azure.clientId }}
  AZURE_CLIENT_SECRET: {{ .Values.outline.authentication.azure.clientSecret }}
  AZURE_RESOURCE_APP_ID: {{ .Values.outline.authentication.azure.app_id }}
  {{ end }}
  {{ if .Values.outline.authentication.slack }}
  SLACK_KEY: {{ .Values.outline.authentication.slack.key }}
  SLACK_SECRET: {{ .Values.outline.authentication.slack.secret }}
  {{ end }}
  {{ if .Values.outline.authentication.oidc }}
  OIDC_CLIENT_ID: {{ .Values.outline.authentication.oidc.clientID }}
  OIDC_CLIENT_SECRET: {{ .Values.outline.authentication.oidc.clientSecret }}
  OIDC_AUTH_URI: {{ .Values.outline.authentication.oidc.authURI }}
  OIDC_TOKEN_URI: {{ .Values.outline.authentication.oidc.tokenURI }}
  OIDC_USERINFO_URI: {{ .Values.outline.authentication.oidc.userInfoURI }}
  OIDC_USERNAME_CLAIM: {{ .Values.outline.authentication.oidc.usernameClaim }}
  OIDC_DISPLAY_NAME: {{ .Values.outline.authentication.oidc.displayName }}
  OIDC_SCOPES: {{ .Values.outline.authentication.oidc.scopes }}
  {{ end }}
  {{ if .Values.outline.authentication.gitlab }}
  OIDC_AUTH_URI: {{ .Values.outline.authentication.gitlab.authURI }}
  OIDC_TOKEN_URI: {{ .Values.outline.authentication.gitlab.tokenURI }}
  OIDC_USERINFO_URI: {{ .Values.outline.authentication.gitlab.userInfoURI }}
  OIDC_USERNAME_CLAIM: {{ .Values.outline.authentication.gitlab.usernameClaim }}
  OIDC_DISPLAY_NAME: {{ .Values.outline.authentication.gitlab.displayName }}
  OIDC_SCOPES: {{ .Values.outline.authentication.gitlab.scopes }}
  {{ end }}
  {{ if .Values.outline.authentication.saml }}
  SAML_SSO_ENDPOINT: {{ .Values.outline.authentication.saml.ssoEndpoint }}
  SAML_CERT: {{ .Values.outline.authentication.saml.cert }}
  {{ end }}
  {{ if .Values.outline.authentication.saml }}
  SAML_SSO_ENDPOINT: {{ .Values.outline.authentication.saml.ssoEndpoint }}
  SAML_CERT: {{ .Values.outline.authentication.saml.cert }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-integration
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.outline.integration.slack }}
  SLACK_VERIFICATION_TOKEN={{ .Values.outline.integration.slack.token }}
  SLACK_APP_ID={{ .Values.outline.integration.slack.appID }}
  SLACK_MESSAGE_ACTIONS={{ .Values.outline.integration.slack.message }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-utils
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY={{ .Values.outline.secrets.key }}
  UTILS_SECRET={{ .Values.outline.integration.slack.secret }}
