apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-s3
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey }}
  AWS_REGION: {{ .Values.s3.region }}
  AWS_S3_UPLOAD_BUCKET_URL: {{ .Values.s3.bucketUrl }}
  AWS_S3_UPLOAD_BUCKET_NAME: {{ .Values.s3.bucketName }}
  AWS_S3_UPLOAD_MAX_SIZE: 26214400
  AWS_S3_FORCE_PATH_STYLE: true
  AWS_S3_ACL: {{ .Values.s3.acl }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-db
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: postgres://{{ .Values.outlineSecrets.db.user }}@{{ .Values.outlineSecrets.db.host }}:5432/{{ .Values.outlineSecrets.db.database }}?sslmode={{ .Values.outlineSecrets.db.sslmode }}&password={{ .Values.outlineSecrets.db.password }}
  DATABASE_CONNECTION_POOL_MIN: {{ .Values.outlineSecrets.db.connectionPoolMin }}
  DATABASE_CONNECTION_POOL_MAX: {{ .Values.outlineSecrets.db.connectionPoolMax }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-redis
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_URL: {{ .Values.outlineSecrets.redis.url }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-mail
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_HOST: {{ .Values.outlineSecrets.mail.host }}
  SMTP_PORT: {{ .Values.outlineSecrets.mail.port }}
  SMTP_USERNAME: {{ .Values.outlineSecrets.mail.user }}
  SMTP_PASSWORD: {{ .Values.outlineSecrets.mail.password }}
  SMTP_FROM_EMAIL: {{ .Values.outlineSecrets.mail.from }}
  SMTP_SECURE: {{ .Values.outlineSecrets.mail.secure }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-authentication
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ if .Values.outlineSecrets.authentication.google }}
  GOOGLE_CLIENT_ID: {{ .Values.outlineSecrets.authentication.google.clientId }}
  GOOGLE_CLIENT_SECRET: {{ .Values.outlineSecrets.authentication.google.clientSecret }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.azure }}
  AZURE_CLIENT_ID: {{ .Values.outlineSecrets.authentication.azure.clientId }}
  AZURE_CLIENT_SECRET: {{ .Values.outlineSecrets.authentication.azure.clientSecret }}
  AZURE_RESOURCE_APP_ID: {{ .Values.outlineSecrets.authentication.azure.app_id }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.azure }}
  AZURE_CLIENT_ID: {{ .Values.outlineSecrets.authentication.azure.clientId }}
  AZURE_CLIENT_SECRET: {{ .Values.outlineSecrets.authentication.azure.clientSecret }}
  AZURE_RESOURCE_APP_ID: {{ .Values.outlineSecrets.authentication.azure.app_id }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.slack }}
  SLACK_KEY: {{ .Values.outlineSecrets.authentication.slack.key }}
  SLACK_SECRET: {{ .Values.outlineSecrets.authentication.slack.secret }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.oidc }}
  OIDC_CLIENT_ID: {{ .Values.outlineSecrets.authentication.oidc.clientID }}
  OIDC_CLIENT_SECRET: {{ .Values.outlineSecrets.authentication.oidc.clientSecret }}
  OIDC_AUTH_URI: {{ .Values.outlineSecrets.authentication.oidc.authURI }}
  OIDC_TOKEN_URI: {{ .Values.outlineSecrets.authentication.oidc.tokenURI }}
  OIDC_USERINFO_URI: {{ .Values.outlineSecrets.authentication.oidc.userInfoURI }}
  OIDC_USERNAME_CLAIM: {{ .Values.outlineSecrets.authentication.oidc.usernameClaim }}
  OIDC_DISPLAY_NAME: {{ .Values.outlineSecrets.authentication.oidc.displayName }}
  OIDC_SCOPES: {{ .Values.outlineSecrets.authentication.oidc.scopes }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.gitlab }}
  OIDC_AUTH_URI: {{ .Values.outlineSecrets.authentication.gitlab.authURI }}
  OIDC_TOKEN_URI: {{ .Values.outlineSecrets.authentication.gitlab.tokenURI }}
  OIDC_USERINFO_URI: {{ .Values.outlineSecrets.authentication.gitlab.userInfoURI }}
  OIDC_USERNAME_CLAIM: {{ .Values.outlineSecrets.authentication.gitlab.usernameClaim }}
  OIDC_DISPLAY_NAME: {{ .Values.outlineSecrets.authentication.gitlab.displayName }}
  OIDC_SCOPES: {{ .Values.outlineSecrets.authentication.gitlab.scopes }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.saml }}
  SAML_SSO_ENDPOINT: {{ .Values.outlineSecrets.authentication.saml.ssoEndpoint }}
  SAML_CERT: {{ .Values.outlineSecrets.authentication.saml.cert }}
  {{ end }}
  {{ if .Values.outlineSecrets.authentication.saml }}
  SAML_SSO_ENDPOINT: {{ .Values.outlineSecrets.authentication.saml.ssoEndpoint }}
  SAML_CERT: {{ .Values.outlineSecrets.authentication.saml.cert }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-slack
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_HOST: {{ .Values.outlineSecrets.mail.host }}
  SMTP_PORT: {{ .Values.outlineSecrets.mail.port }}
  SMTP_USERNAME: {{ .Values.outlineSecrets.mail.user }}
  SMTP_PASSWORD: {{ .Values.outlineSecrets.mail.password }}
  SMTP_FROM_EMAIL: {{ .Values.outlineSecrets.mail.from }}
  SMTP_SECURE: {{ .Values.outlineSecrets.mail.secure }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outline.fullname" . }}-config
  labels:
    {{- include "outline.labels" . | nindent 4 }}
type: Opaque
stringData:
  ALLOWED_DOMAINS: {{ .Values.outlineSecrets.config.allowedDomains }}
  COLLABORATION_URL: {{ .Values.outlineSecrets.config.collaborationURL }}
  DEBUG: {{ .Values.outlineSecrets.config.debug }}
  DEFAULT_LANGUAGE: {{ .Values.outlineSecrets.config.defaultLanguage }}
  ENABLE_UPDATES: {{ .Values.outlineSecrets.config.enableUpdates }}
  FORCE_HTTPS: {{ .Values.outlineSecrets.config.forceHTTPS }}
  GOOGLE_ANALYTICS_ID: {{ .Values.outlineSecrets.config.googleAnalyticsId }}
  MAXIMUM_IMPORT_SIZE: {{ .Values.outlineSecrets.config.maxImportSize }}
  SENTRY_DSN: {{ .Values.outlineSecrets.config.sentryDSN }}
  TEAM_LOGO: {{ .Values.outlineSecrets.config.teamLogo }}
  URL: {{ .Values.outlineSecrets.config.url }}
  WEB_CONCURRENCY: {{ .Values.outlineSecrets.config.webConcurrency }}
