name: module tests

on:
  push:
    branches:
      - "**"
    paths:
      - .github/workflows/helm_execserver_tests.yml
      - charts/execserver/**

env:
  minikube_version: 'v1.26.0'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.5.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        env:
          EXTRA_ARGS: "--target-branch ${{ github.event.repository.default_branch }}"
        run: make lint

  integration-tests-nginx:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - kubernetes_version: 'v1.20.15'
          - kubernetes_version: 'v1.21.9'
          - kubernetes_version: 'v1.22.6'
          - kubernetes_version: 'v1.23.3'
          - kubernetes_version: 'v1.24.1'
    env:
      work_dir: ./charts/execserver
      TMUX_SESSION_NAME: execserver-tests
      NAMESPACE: "default"
      SERVICE_NAME: "ex1"
      VALIDATION_SERVICES: "node,convert,ffmpeg,soffice,metadata,pdf2pages,xslt,copy,iiif"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Install tmux
        run: |
          sudo apt-get install tmux -y
      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.5.1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: ${{ env.minikube_version }}
          kubernetes version: ${{ matrix.kubernetes_version }}

      - name: Enable Minikube Addons
        run: |
          minikube addons enable ingress
          minikube addons enable csi-hostpath-driver
          minikube addons enable metrics-server
      - name: Print context
        run: kubectl config get-contexts

      - name: Run chart-testing (install)
        run: make install